#!/bin/bash
# This script starts Kepler.
# Run with -h to see all command-line options.
# This script is auto-generated by the 'ant make-startup-script' command.

CUR_DIR=`pwd`
SCRIPT_DIR="$(dirname "$(readlink "$0")")"
cd $SCRIPT_DIR
java -classpath build-area/lib/ant.jar:kepler.jar org.kepler.build.runner.Kepler ${args} "$@"
cd $CUR_DIR
